import { FormValidationResult } from "@mantine/form/lib/types";
import { SetStateAction } from "react";

// Handle Gather Save
export const handleGatherSave = async (
	resource: string,
	isValid: any,
	projectid: string,
	setLoading: (value: SetStateAction<boolean>) => void,
	mutate: any,
	translate: any,
	formValues: any,
	setInputList: (value: SetStateAction<string[]>) => void,
	reset: () => void,
	router: any,
	validate: () => FormValidationResult,
	id?: string
) => {
	if (isValid()) {
		if (projectid) {
			setLoading(true);
			mutate(
				{
					resource,
					id,
					values: formValues,
					errorNotification: (res: any) => {
						let message = translate("gathers.errors.create");
						if (res?.response?.data?.detail[0]?.msg) {
							message = res.response.data.detail[0].msg;
						}
						return {
							message,
							description: "Error",
							type: "error",
						};
					},
					successNotification: () => {
						let message = "";
						if (id) {
							message = translate("gathers.success.update");
						} else {
							message = translate("gathers.success.create");
						}
						return {
							message,
							description: "Success",
							type: "success",
						};
					},
				},
				{
					onSuccess: async (res: any) => {
						await Promise.all([setInputList([]), reset()]);
						setTimeout(() => {
							router.push(
								`/projects/${projectid}/gathers/${res?.data?.child_type}/${res?.data?.id}`
							);
						}, 1000);
					},
					onError: () => {
						setLoading(false);
					},
				}
			);
		}
	} else {
		validate();
	}
};

// Country List
export const countryList = [
	{ value: "None", label: "None" },
	{ value: "AF", label: "Afghanistan" },
	{ value: "AL", label: "Albania" },
	{ value: "DZ", label: "Algeria" },
	{ value: "AS", label: "American Samoa" },
	{ value: "AD", label: "Andorra" },
	{ value: "AO", label: "Angola" },
	{ value: "AI", label: "Anguilla" },
	{ value: "AQ", label: "Antarctica" },
	{ value: "AG", label: "Antigua and Barbuda" },
	{ value: "AR", label: "Argentina" },
	{ value: "AM", label: "Armenia" },
	{ value: "AW", label: "Aruba" },
	{ value: "AU", label: "Australia" },
	{ value: "AT", label: "Austria" },
	{ value: "AZ", label: "Azerbaijan" },
	{ value: "BS", label: "Bahamas" },
	{ value: "BH", label: "Bahrain" },
	{ value: "BD", label: "Bangladesh" },
	{ value: "BB", label: "Barbados" },
	{ value: "BY", label: "Belarus" },
	{ value: "BE", label: "Belgium" },
	{ value: "BZ", label: "Belize" },
	{ value: "BJ", label: "Benin" },
	{ value: "BM", label: "Bermuda" },
	{ value: "BT", label: "Bhutan" },
	{ value: "BO", label: "Bolivia" },
	{ value: "BQ", label: "Bonaire, Sint Eustatius and Saba" },
	{ value: "BA", label: "Bosnia and Herzegovina" },
	{ value: "BW", label: "Botswana" },
	{ value: "BV", label: "Bouvet Island" },
	{ value: "BR", label: "Brazil" },
	{ value: "IO", label: "British Indian Ocean Territory" },
	{ value: "VG", label: "Virgin Islands (British)" },
	{ value: "BN", label: "Brunei Darussalam" },
	{ value: "BG", label: "Bulgaria" },
	{ value: "BF", label: "Burkina Faso" },
	{ value: "BI", label: "Burundi" },
	{ value: "KH", label: "Cambodia" },
	{ value: "CM", label: "Cameroon" },
	{ value: "CA", label: "Canada" },
	{ value: "CV", label: "Cape Verde" },
	{ value: "KY", label: "Cayman Islands" },
	{ value: "CF", label: "Central African Republic" },
	{ value: "TD", label: "Chad" },
	{ value: "CL", label: "Chile" },
	{ value: "CN", label: "China" },
	{ value: "CX", label: "Christmas Island" },
	{ value: "CC", label: "Cocos (Keeling) Islands" },
	{ value: "CO", label: "Colombia" },
	{ value: "KM", label: "Comoros" },
	{ value: "CK", label: "Cook Islands" },
	{ value: "CR", label: "Costa Rica" },
	{ value: "HR", label: "Croatia" },
	{ value: "CU", label: "Cuba" },
	{ value: "CW", label: "Curaçao" },
	{ value: "CY", label: "Cyprus" },
	{ value: "CZ", label: "Czech Republic" },
	{ value: "CD", label: "Democratic Republic of the Congo" },
	{ value: "DK", label: "Denmark" },
	{ value: "DJ", label: "Djibouti" },
	{ value: "DM", label: "Dominica" },
	{ value: "DO", label: "Dominican Republic" },
	{ value: "TL", label: "East Timor" },
	{ value: "EC", label: "Ecuador" },
	{ value: "EG", label: "Egypt" },
	{ value: "SV", label: "El Salvador" },
	{ value: "GQ", label: "Equatorial Guinea" },
	{ value: "ER", label: "Eritrea" },
	{ value: "EE", label: "Estonia" },
	{ value: "ET", label: "Ethiopia" },
	{ value: "FK", label: "Falkland Islands" },
	{ value: "FO", label: "Faroe Islands" },
	{ value: "FJ", label: "Fiji" },
	{ value: "FI", label: "Finland" },
	{ value: "FR", label: "France" },
	{ value: "GF", label: "French Guiana" },
	{ value: "PF", label: "French Polynesia" },
	{ value: "TF", label: "French Southern Territories" },
	{ value: "GA", label: "Gabon" },
	{ value: "GM", label: "Gambia" },
	{ value: "GE", label: "Georgia" },
	{ value: "DE", label: "Germany" },
	{ value: "GH", label: "Ghana" },
	{ value: "GI", label: "Gibraltar" },
	{ value: "GR", label: "Greece" },
	{ value: "GL", label: "Greenland" },
	{ value: "GD", label: "Grenada" },
	{ value: "GP", label: "Guadeloupe" },
	{ value: "GU", label: "Guam" },
	{ value: "GT", label: "Guatemala" },
	{ value: "GG", label: "Guernsey" },
	{ value: "GN", label: "Guinea" },
	{ value: "GW", label: "Guinea-Bissau" },
	{ value: "GY", label: "Guyana" },
	{ value: "HT", label: "Haiti" },
	{ value: "HM", label: "Heard Island and McDonald Islands" },
	{ value: "HN", label: "Honduras" },
	{ value: "HK", label: "Hong Kong" },
	{ value: "HU", label: "Hungary" },
	{ value: "IS", label: "Iceland" },
	{ value: "IN", label: "India" },
	{ value: "ID", label: "Indonesia" },
	{ value: "IR", label: "Iran" },
	{ value: "IQ", label: "Iraq" },
	{ value: "IE", label: "Ireland" },
	{ value: "IM", label: "Isle of Man" },
	{ value: "IL", label: "Israel" },
	{ value: "IT", label: "Italy" },
	{ value: "CI", label: "Ivory Coast" },
	{ value: "JM", label: "Jamaica" },
	{ value: "JP", label: "Japan" },
	{ value: "JE", label: "Jersey" },
	{ value: "JO", label: "Jordan" },
	{ value: "KZ", label: "Kazakhstan" },
	{ value: "KE", label: "Kenya" },
	{ value: "KI", label: "Kiribati" },
	{ value: "XK", label: "Kosovo" },
	{ value: "KW", label: "Kuwait" },
	{ value: "KG", label: "Kyrgyzstan" },
	{ value: "LA", label: "Laos" },
	{ value: "LV", label: "Latvia" },
	{ value: "LB", label: "Lebanon" },
	{ value: "LS", label: "Lesotho" },
	{ value: "LR", label: "Liberia" },
	{ value: "LY", label: "Libya" },
	{ value: "LI", label: "Liechtenstein" },
	{ value: "LT", label: "Lithuania" },
	{ value: "LU", label: "Luxembourg" },
	{ value: "MO", label: "Macau" },
	{ value: "MG", label: "Madagascar" },
	{ value: "MW", label: "Malawi" },
	{ value: "MY", label: "Malaysia" },
	{ value: "MV", label: "Maldives" },
	{ value: "ML", label: "Mali" },
	{ value: "MT", label: "Malta" },
	{ value: "MH", label: "Marshall Islands" },
	{ value: "MQ", label: "Martinique" },
	{ value: "MR", label: "Mauritania" },
	{ value: "MU", label: "Mauritius" },
	{ value: "YT", label: "Mayotte" },
	{ value: "MX", label: "Mexico" },
	{ value: "FM", label: "Micronesia" },
	{ value: "MD", label: "Moldova" },
	{ value: "MC", label: "Monaco" },
	{ value: "MN", label: "Mongolia" },
	{ value: "ME", label: "Montenegro" },
	{ value: "MS", label: "Montserrat" },
	{ value: "MA", label: "Morocco" },
	{ value: "MZ", label: "Mozambique" },
	{ value: "MM", label: "Myanmar" },
	{ value: "NA", label: "Namibia" },
	{ value: "NR", label: "Nauru" },
	{ value: "NP", label: "Nepal" },
	{ value: "NL", label: "Netherlands" },
	{ value: "NC", label: "New Caledonia" },
	{ value: "NZ", label: "New Zealand" },
	{ value: "NI", label: "Nicaragua" },
	{ value: "NE", label: "Niger" },
	{ value: "NG", label: "Nigeria" },
	{ value: "NU", label: "Niue" },
	{ value: "NF", label: "Norfolk Island" },
	{ value: "KP", label: "North Korea" },
	{ value: "MK", label: "North Macedonia" },
	{ value: "MP", label: "Northern Mariana Islands" },
	{ value: "NO", label: "Norway" },
	{ value: "OM", label: "Oman" },
	{ value: "PK", label: "Pakistan" },
	{ value: "PW", label: "Palau" },
	{ value: "PS", label: "Palestine" },
	{ value: "PA", label: "Panama" },
	{ value: "PG", label: "Papua New Guinea" },
	{ value: "PY", label: "Paraguay" },
	{ value: "PE", label: "Peru" },
	{ value: "PH", label: "Philippines" },
	{ value: "PN", label: "Pitcairn" },
	{ value: "PL", label: "Poland" },
	{ value: "PT", label: "Portugal" },
	{ value: "PR", label: "Puerto Rico" },
	{ value: "QA", label: "Qatar" },
	{ value: "CG", label: "Republic of the Congo" },
	{ value: "RO", label: "Romania" },
	{ value: "RU", label: "Russia" },
	{ value: "RW", label: "Rwanda" },
	{ value: "RE", label: "Réunion" },
	{ value: "BL", label: "Saint Barthélemy" },
	{ value: "SH", label: "Saint Helena" },
	{ value: "KN", label: "Saint Kitts and Nevis" },
	{ value: "LC", label: "Saint Lucia" },
	{ value: "MF", label: "Saint Martin" },
	{ value: "PM", label: "Saint Pierre and Miquelon" },
	{ value: "VC", label: "Saint Vincent and the Grenadines" },
	{ value: "WS", label: "Samoa" },
	{ value: "SM", label: "San Marino" },
	{ value: "SA", label: "Saudi Arabia" },
	{ value: "SN", label: "Senegal" },
	{ value: "RS", label: "Serbia" },
	{ value: "SC", label: "Seychelles" },
	{ value: "SL", label: "Sierra Leone" },
	{ value: "SG", label: "Singapore" },
	{ value: "SX", label: "Sint Maarten" },
	{ value: "SK", label: "Slovakia" },
	{ value: "SI", label: "Slovenia" },
	{ value: "SB", label: "Solomon Islands" },
	{ value: "SO", label: "Somalia" },
	{ value: "ZA", label: "South Africa" },
	{ value: "GS", label: "South Georgia and the South Sandwich Islands" },
	{ value: "KR", label: "South Korea" },
	{ value: "SS", label: "South Sudan" },
	{ value: "ES", label: "Spain" },
	{ value: "LK", label: "Sri Lanka" },
	{ value: "SD", label: "Sudan" },
	{ value: "SR", label: "Suriname" },
	{ value: "SJ", label: "Svalbard and Jan Mayen" },
	{ value: "SZ", label: "Eswatini" },
	{ value: "SE", label: "Sweden" },
	{ value: "CH", label: "Switzerland" },
	{ value: "SY", label: "Syria" },
	{ value: "ST", label: "São Tomé and Príncipe" },
	{ value: "TW", label: "Taiwan" },
	{ value: "TJ", label: "Tajikistan" },
	{ value: "TZ", label: "Tanzania" },
	{ value: "TH", label: "Thailand" },
	{ value: "TG", label: "Togo" },
	{ value: "TK", label: "Tokelau" },
	{ value: "TO", label: "Tonga" },
	{ value: "TT", label: "Trinidad and Tobago" },
	{ value: "TN", label: "Tunisia" },
	{ value: "TR", label: "Turkey" },
	{ value: "TM", label: "Turkmenistan" },
	{ value: "TC", label: "Turks and Caicos Islands" },
	{ value: "TV", label: "Tuvalu" },
	{ value: "UM", label: "United States Minor Outlying Islands" },
	{ value: "VI", label: "Virgin Islands (U.S.)" },
	{ value: "UG", label: "Uganda" },
	{ value: "UA", label: "Ukraine" },
	{ value: "AE", label: "United Arab Emirates" },
	{ value: "GB", label: "United Kingdom" },
	{ value: "US", label: "United States" },
	{ value: "UY", label: "Uruguay" },
	{ value: "UZ", label: "Uzbekistan" },
	{ value: "VU", label: "Vanuatu" },
	{ value: "VA", label: "Vatican City" },
	{ value: "VE", label: "Venezuela" },
	{ value: "VN", label: "Vietnam" },
	{ value: "WF", label: "Wallis and Futuna" },
	{ value: "EH", label: "Western Sahara" },
	{ value: "YE", label: "Yemen" },
	{ value: "ZM", label: "Zambia" },
	{ value: "ZW", label: "Zimbabwe" },
	{ value: "AX", label: "Åland Islands" },
];

export const danekCountryList = [
	{ value: "us", label: "United States" },
	{ value: "vn", label: "Vietnam" },
	{ value: "br", label: "Brazil" },
	{ value: "gb", label: "United Kingdom" },
	{ value: "de", label: "Germany" },
	{ value: "ar", label: "Argentina" },
	{ value: "ca", label: "Canada" },
	{ value: "id", label: "Indonesia" },
	{ value: "it", label: "Italy" },
	{ value: "ec", label: "Ecuador" },
	{ value: "es", label: "Spain" },
	{ value: "ph", label: "Philippines" },
	{ value: "ru", label: "Russia" },
	{ value: "fr", label: "France" },
	{ value: "eg", label: "Egypt" },
	{ value: "mx", label: "Mexico" },
	{ value: "pl", label: "Poland" },
	{ value: "ro", label: "Romania" },
	{ value: "iq", label: "Iraq" },
	{ value: "za", label: "South Africa" },
	{ value: "in", label: "India" },
	{ value: "au", label: "Australia" },
	{ value: "jp", label: "Japan" },
	{ value: "pe", label: "Peru" },
	{ value: "ua", label: "Ukraine" },
	{ value: "cl", label: "Chile" },
	{ value: "hk", label: "Hong Kong" },
	{ value: "tr", label: "Turkey" },
	{ value: "nl", label: "Netherlands" },
	{ value: "my", label: "Malaysia" },
	{ value: "co", label: "Colombia" },
	{ value: "se", label: "Sweden" },
	{ value: "tt", label: "Trinidad and Tobago" },
	{ value: "pt", label: "Portugal" },
	{ value: "sa", label: "Saudi Arabia" },
	{ value: "th", label: "Thailand" },
	{ value: "sg", label: "Singapore" },
	{ value: "ve", label: "Venezuela" },
	{ value: "kr", label: "South Korea" },
	{ value: "rs", label: "Serbia" },
	{ value: "cn", label: "China" },
	{ value: "hu", label: "Hungary" },
	{ value: "ke", label: "Kenya" },
	{ value: "jm", label: "Jamaica" },
	{ value: "ch", label: "Switzerland" },
	{ value: "fi", label: "Finland" },
	{ value: "ie", label: "Ireland" },
	{ value: "bg", label: "Bulgaria" },
	{ value: "dz", label: "Algeria" },
	{ value: "do", label: "Dominican Republic" },
	{ value: "pk", label: "Pakistan" },
	{ value: "bd", label: "Bangladesh" },
	{ value: "bo", label: "Bolivia" },
	{ value: "tw", label: "Taiwan" },
	{ value: "at", label: "Austria" },
	{ value: "gr", label: "Greece" },
	{ value: "uz", label: "Uzbekistan" },
	{ value: "lv", label: "Latvia" },
	{ value: "il", label: "Israel" },
	{ value: "bb", label: "Barbados" },
	{ value: "kz", label: "Kazakhstan" },
	{ value: "lk", label: "Sri Lanka" },
	{ value: "be", label: "Belgium" },
	{ value: "dk", label: "Denmark" },
	{ value: "az", label: "Azerbaijan" },
	{ value: "cz", label: "Czech Republic" },
	{ value: "nz", label: "New Zealand" },
	{ value: "pr", label: "Puerto Rico" },
	{ value: "py", label: "Paraguay" },
	{ value: "gt", label: "Guatemala" },
	{ value: "hn", label: "Honduras" },
	{ value: "jo", label: "Jordan" },
	{ value: "ma", label: "Morocco" },
	{ value: "ir", label: "Iran" },
	{ value: "pa", label: "Panama" },
	{ value: "ae", label: "United Arab Emirates" },
	{ value: "no", label: "Norway" },
	{ value: "sk", label: "Slovakia" },
	{ value: "al", label: "Albania" },
	{ value: "bs", label: "Bahamas" },
	{ value: "am", label: "Armenia" },
	{ value: "sv", label: "El Salvador" },
	{ value: "ee", label: "Estonia" },
	{ value: "uy", label: "Uruguay" },
	{ value: "cr", label: "Costa Rica" },
	{ value: "lb", label: "Lebanon" },
	{ value: "hr", label: "Croatia" },
	{ value: "lt", label: "Lithuania" },
	{ value: "md", label: "Moldova" },
	{ value: "np", label: "Nepal" },
	{ value: "ly", label: "Libya" },
	{ value: "ba", label: "Bosnia and Herzegovina" },
	{ value: "kw", label: "Kuwait" },
	{ value: "tn", label: "Tunisia" },
	{ value: "mk", label: "North Macedonia" },
	{ value: "ge", label: "Georgia" },
	{ value: "om", label: "Oman" },
	{ value: "is", label: "Iceland" },
	{ value: "sy", label: "Syria" },
	{ value: "bw", label: "Botswana" },
	{ value: "cy", label: "Cyprus" },
	{ value: "mm", label: "Myanmar" },
	{ value: "by", label: "Belarus" },
	{ value: "ci", label: "Ivory Coast" },
	{ value: "kh", label: "Cambodia" },
	{ value: "qa", label: "Qatar" },
	{ value: "ni", label: "Nicaragua" },
	{ value: "sn", label: "Senegal" },
	{ value: "cw", label: "Curaçao" },
	{ value: "si", label: "Slovenia" },
	{ value: "gy", label: "Guyana" },
	{ value: "bh", label: "Bahrain" },
	{ value: "et", label: "Ethiopia" },
	{ value: "mu", label: "Mauritius" },
	{ value: "kg", label: "Kyrgyzstan" },
	{ value: "ps", label: "Palestine" },
	{ value: "lc", label: "Saint Lucia" },
	{ value: "bz", label: "Belize" },
	{ value: "xk", label: "Kosovo" },
	{ value: "mt", label: "Malta" },
	{ value: "vi", label: "Virgin Islands (U.S.)" },
	{ value: "gd", label: "Grenada" },
	{ value: "gh", label: "Ghana" },
	{ value: "ng", label: "Nigeria" },
	{ value: "bm", label: "Bermuda" },
	{ value: "ky", label: "Cayman Islands" },
	{ value: "ag", label: "Antigua and Barbuda" },
	{ value: "ml", label: "Mali" },
	{ value: "cg", label: "Republic of the Congo" },
	{ value: "sd", label: "Sudan" },
	{ value: "vc", label: "Saint Vincent and the Grenadines" },
	{ value: "tz", label: "Tanzania" },
	{ value: "aw", label: "Aruba" },
	{ value: "me", label: "Montenegro" },
	{ value: "ye", label: "Yemen" },
	{ value: "re", label: "Réunion" },
	{ value: "bn", label: "Brunei Darussalam" },
	{ value: "ga", label: "Gabon" },
	{ value: "ao", label: "Angola" },
	{ value: "vg", label: "Virgin Islands (British)" },
	{ value: "la", label: "Laos" },
	{ value: "cd", label: "Democratic Republic of the Congo" },
	{ value: "bf", label: "Burkina Faso" },
	{ value: "tj", label: "Tajikistan" },
	{ value: "ug", label: "Uganda" },
	{ value: "tg", label: "Togo" },
	{ value: "lu", label: "Luxembourg" },
	{ value: "fj", label: "Fiji" },
	{ value: "sr", label: "Suriname" },
	{ value: "im", label: "Isle of Man" },
	{ value: "mn", label: "Mongolia" },
	{ value: "mo", label: "Macau" },
	{ value: "gp", label: "Guadeloupe" },
	{ value: "sl", label: "Sierra Leone" },
	{ value: "je", label: "Jersey" },
	{ value: "kn", label: "Saint Kitts and Nevis" },
	{ value: "mq", label: "Martinique" },
	{ value: "mv", label: "Maldives" },
	{ value: "dm", label: "Dominica" },
	{ value: "gu", label: "Guam" },
	{ value: "cv", label: "Cape Verde" },
	{ value: "rw", label: "Rwanda" },
	{ value: "mz", label: "Mozambique" },
	{ value: "gg", label: "Guernsey" },
	{ value: "mw", label: "Malawi" },
	{ value: "zm", label: "Zambia" },
	{ value: "zw", label: "Zimbabwe" },
	{ value: "cm", label: "Cameroon" },
	{ value: "gf", label: "French Guiana" },
	{ value: "cu", label: "Cuba" },
	{ value: "tc", label: "Turks and Caicos Islands" },
	{ value: "ad", label: "Andorra" },
	{ value: "so", label: "Somalia" },
	{ value: "bj", label: "Benin" },
	{ value: "sx", label: "Sint Maarten" },
	{ value: "gm", label: "Gambia" },
	{ value: "bt", label: "Bhutan" },
	{ value: "na", label: "Namibia" },
	{ value: "mr", label: "Mauritania" },
	{ value: "sc", label: "Seychelles" },
	{ value: "af", label: "Afghanistan" },
	{ value: "bq", label: "Bonaire, Sint Eustatius and Saba" },
	{ value: "gi", label: "Gibraltar" },
	{ value: "sz", label: "Eswatini" },
	{ value: "mf", label: "Saint Martin" },
	{ value: "nc", label: "New Caledonia" },
	{ value: "ht", label: "Haiti" },
	{ value: "pf", label: "French Polynesia" },
	{ value: "tm", label: "Turkmenistan" },
	{ value: "st", label: "São Tomé and Príncipe" },
	{ value: "ai", label: "Anguilla" },
	{ value: "mg", label: "Madagascar" },
	{ value: "ms", label: "Montserrat" },
	{ value: "gn", label: "Guinea" },
	{ value: "sm", label: "San Marino" },
	{ value: "ss", label: "South Sudan" },
	{ value: "gq", label: "Equatorial Guinea" },
	{ value: "li", label: "Liechtenstein" },
	{ value: "pg", label: "Papua New Guinea" },
	{ value: "mc", label: "Monaco" },
	{ value: "tl", label: "East Timor" },
	{ value: "wf", label: "Wallis and Futuna" },
	{ value: "bi", label: "Burundi" },
	{ value: "gl", label: "Greenland" },
	{ value: "ne", label: "Niger" },
	{ value: "ls", label: "Lesotho" },
	{ value: "ck", label: "Cook Islands" },
	{ value: "km", label: "Comoros" },
	{ value: "dj", label: "Djibouti" },
	{ value: "as", label: "American Samoa" },
	{ value: "td", label: "Chad" },
];

export const tiktokCountryList = [
	{ value: "None", label: "None" },
	{ value: "AF", label: "Afghanistan" },
	{ value: "AL", label: "Albania" },
	{ value: "DZ", label: "Algeria" },
	{ value: "AS", label: "American Samoa" },
	{ value: "AD", label: "Andorra" },
	{ value: "AO", label: "Angola" },
	{ value: "AI", label: "Anguilla" },
	{ value: "AG", label: "Antigua and Barbuda" },
	{ value: "AR", label: "Argentina" },
	{ value: "AM", label: "Armenia" },
	{ value: "AU", label: "Australia" },
	{ value: "AT", label: "Austria" },
	{ value: "AZ", label: "Azerbaijan" },
	{ value: "BS", label: "Bahamas" },
	{ value: "BH", label: "Bahrain" },
	{ value: "BD", label: "Bangladesh" },
	{ value: "BB", label: "Barbados" },
	{ value: "BY", label: "Belarus" },
	{ value: "BE", label: "Belgium" },
	{ value: "BZ", label: "Belize" },
	{ value: "BJ", label: "Benin" },
	{ value: "BM", label: "Bermuda" },
	{ value: "BT", label: "Bhutan" },
	{ value: "BO", label: "Bolivia" },
	{ value: "BA", label: "Bosnia and Herzegovina" },
	{ value: "BW", label: "Botswana" },
	{ value: "BR", label: "Brazil" },
	{ value: "VG", label: "British Virgin Islands" },
	{ value: "BN", label: "Brunei" },
	{ value: "BG", label: "Bulgaria" },
	{ value: "BF", label: "Burkina Faso" },
	{ value: "BI", label: "Burundi" },
	{ value: "KH", label: "Cambodia" },
	{ value: "CM", label: "Cameroon" },
	{ value: "CA", label: "Canada" },
	{ value: "CV", label: "Cape Verde" },
	{ value: "KY", label: "Cayman Islands" },
	{ value: "TD", label: "Chad" },
	{ value: "CL", label: "Chile" },
	{ value: "CO", label: "Colombia" },
	{ value: "CK", label: "Cook Islands" },
	{ value: "CR", label: "Costa Rica" },
	{ value: "HR", label: "Croatia" },
	{ value: "CY", label: "Cyprus" },
	{ value: "CZ", label: "Czech Republic" },
	{ value: "CD", label: "Democratic Republic of the Congo" },
	{ value: "DK", label: "Denmark" },
	{ value: "DJ", label: "Djibouti" },
	{ value: "DO", label: "Dominican Republic" },
	{ value: "EC", label: "Ecuador" },
	{ value: "EG", label: "Egypt" },
	{ value: "SV", label: "El Salvador" },
	{ value: "EE", label: "Estonia" },
	{ value: "ET", label: "Ethiopia" },
	{ value: "FK", label: "Falkland Islands" },
	{ value: "FJ", label: "Fiji" },
	{ value: "FI", label: "Finland" },
	{ value: "FR", label: "France" },
	{ value: "PF", label: "French Polynesia" },
	{ value: "GA", label: "Gabon" },
	{ value: "GE", label: "Georgia" },
	{ value: "DE", label: "Germany" },
	{ value: "GH", label: "Ghana" },
	{ value: "GI", label: "Gibraltar" },
	{ value: "GR", label: "Greece" },
	{ value: "GL", label: "Greenland" },
	{ value: "GD", label: "Grenada" },
	{ value: "GP", label: "Guadeloupe" },
	{ value: "GT", label: "Guatemala" },
	{ value: "GN", label: "Guinea" },
	{ value: "GW", label: "Guinea-Bissau" },
	{ value: "GY", label: "Guyana" },
	{ value: "HN", label: "Honduras" },
	{ value: "HK", label: "Hong Kong" },
	{ value: "HU", label: "Hungary" },
	{ value: "IS", label: "Iceland" },
	{ value: "IN", label: "India" },
	{ value: "ID", label: "Indonesia" },
	{ value: "IQ", label: "Iraq" },
	{ value: "IE", label: "Ireland" },
	{ value: "IM", label: "Isle of Man" },
	{ value: "IL", label: "Israel" },
	{ value: "IT", label: "Italy" },
	{ value: "CI", label: "Ivory Coast" },
	{ value: "JM", label: "Jamaica" },
	{ value: "JP", label: "Japan" },
	{ value: "JE", label: "Jersey" },
	{ value: "KZ", label: "Kazakhstan" },
	{ value: "KE", label: "Kenya" },
	{ value: "XK", label: "Kosovo" },
	{ value: "KW", label: "Kuwait" },
	{ value: "LA", label: "Laos" },
	{ value: "LV", label: "Latvia" },
	{ value: "LB", label: "Lebanon" },
	{ value: "LS", label: "Lesotho" },
	{ value: "LR", label: "Liberia" },
	{ value: "LY", label: "Libya" },
	{ value: "LT", label: "Lithuania" },
	{ value: "LU", label: "Luxembourg" },
	{ value: "MO", label: "Macao" },
	{ value: "MG", label: "Madagascar" },
	{ value: "MW", label: "Malawi" },
	{ value: "MY", label: "Malaysia" },
	{ value: "MV", label: "Maldives" },
	{ value: "ML", label: "Mali" },
	{ value: "MT", label: "Malta" },
	{ value: "MH", label: "Marshall Islands" },
	{ value: "MQ", label: "Martinique" },
	{ value: "MR", label: "Mauritania" },
	{ value: "MU", label: "Mauritius" },
	{ value: "MX", label: "Mexico" },
	{ value: "MD", label: "Moldova" },
	{ value: "MC", label: "Monaco" },
	{ value: "MN", label: "Mongolia" },
	{ value: "ME", label: "Montenegro" },
	{ value: "MA", label: "Morocco" },
	{ value: "MZ", label: "Mozambique" },
	{ value: "MM", label: "Myanmar" },
	{ value: "NA", label: "Namibia" },
	{ value: "NR", label: "Nauru" },
	{ value: "NP", label: "Nepal" },
	{ value: "NL", label: "Netherlands" },
	{ value: "NZ", label: "New Zealand" },
	{ value: "NI", label: "Nicaragua" },
	{ value: "NG", label: "Nigeria" },
	{ value: "MK", label: "North Macedonia" },
	{ value: "NO", label: "Norway" },
	{ value: "OM", label: "Oman" },
	{ value: "PK", label: "Pakistan" },
	{ value: "PS", label: "Palestine" },
	{ value: "PA", label: "Panama" },
	{ value: "PG", label: "Papua New Guinea" },
	{ value: "PY", label: "Paraguay" },
	{ value: "PE", label: "Peru" },
	{ value: "PH", label: "Philippines" },
	{ value: "PL", label: "Poland" },
	{ value: "PT", label: "Portugal" },
	{ value: "PR", label: "Puerto Rico" },
	{ value: "QA", label: "Qatar" },
	{ value: "CG", label: "Republic of the Congo" },
	{ value: "RO", label: "Romania" },
	{ value: "RU", label: "Russia" },
	{ value: "RW", label: "Rwanda" },
	{ value: "RE", label: "Réunion" },
	{ value: "KN", label: "Saint Kitts and Nevis" },
	{ value: "LC", label: "Saint Lucia" },
	{ value: "MF", label: "Saint Martin" },
	{ value: "PM", label: "Saint Pierre and Miquelon" },
	{ value: "VC", label: "Saint Vincent and the Grenadines" },
	{ value: "SM", label: "San Marino" },
	{ value: "SA", label: "Saudi Arabia" },
	{ value: "SN", label: "Senegal" },
	{ value: "RS", label: "Serbia" },
	{ value: "SL", label: "Sierra Leone" },
	{ value: "SG", label: "Singapore" },
	{ value: "SX", label: "Sint Maarten" },
	{ value: "SK", label: "Slovakia" },
	{ value: "SB", label: "Solomon Islands" },
	{ value: "SO", label: "Somalia" },
	{ value: "ZA", label: "South Africa" },
	{ value: "KR", label: "South Korea" },
	{ value: "ES", label: "Spain" },
	{ value: "LK", label: "Sri Lanka" },
	{ value: "SR", label: "Suriname" },
	{ value: "SZ", label: "Eswatini" },
	{ value: "SE", label: "Sweden" },
	{ value: "CH", label: "Switzerland" },
	{ value: "TW", label: "Taiwan" },
	{ value: "TJ", label: "Tajikistan" },
	{ value: "TZ", label: "Tanzania" },
	{ value: "TH", label: "Thailand" },
	{ value: "TG", label: "Togo" },
	{ value: "TO", label: "Tonga" },
	{ value: "TT", label: "Trinidad and Tobago" },
	{ value: "TN", label: "Tunisia" },
	{ value: "TR", label: "Turkey" },
	{ value: "TM", label: "Turkmenistan" },
	{ value: "TC", label: "Turks and Caicos Islands" },
	{ value: "TV", label: "Tuvalu" },
	{ value: "VI", label: "U.S. Virgin Islands" },
	{ value: "UG", label: "Uganda" },
	{ value: "UA", label: "Ukraine" },
	{ value: "AE", label: "United Arab Emirates" },
	{ value: "GB", label: "United Kingdom" },
	{ value: "US", label: "United States" },
	{ value: "UY", label: "Uruguay" },
	{ value: "VE", label: "Venezuela" },
	{ value: "VN", label: "Vietnam" },
	{ value: "WF", label: "Wallis and Futuna" },
	{ value: "YE", label: "Yemen" },
	{ value: "ZM", label: "Zambia" },
	{ value: "ZW", label: "Zimbabwe" },
	{ value: "AX", label: "Åland Islands" },
];

// Hashtag BaseURL
export const hashTagPostBaseLink =
	"https://www.tiktok.com/search/video?q=%23{{ input }}";

// Tiktok Searches BaseURL
export const searchPostBaseLink =
	"https://www.tiktok.com/search/video?q={{ input }}";

// Tiktok account Search BaseURL
export const tiktokAccountSearchBaseLink =
	"https://www.tiktok.com/search/user?q=@{{ input }}";

export const facebookSearchPostBaseLink =
	"https://www.facebook.com/search/posts?q={{ input }}";

export const instagramAccountBaseLink =
	"https://www.instagram.com/{{ input }}/";

export const xAdvancedSearchBaseLink =
	"https://x.com/search?q={{ input }}&src=typed_query&f=live";

/**
 * Replaces placeholders in a template string with corresponding values from an object.
 *
 * @param {string} template - The template string containing placeholders in the format {{ key }}.
 * @param {Object} values - An object containing key-value pairs to replace placeholders.
 * @returns {string} - The resulting string with placeholders replaced by corresponding values.
 *
 * @example
 * const template = "Hello, {{ name }}! Welcome to {{ place }}.";
 * const values = { name: "John", place: "Tokyo" };
 * const result = templateString(template, values);
 * console.log(result);  // Output: "Hello, John! Welcome to Tokyo."
 */
export const templateString = (template: string, values: any) =>
	template.replace(/\{\{(.*?)\}\}/g, (match, key) => values[key.trim()] || "");
