"""add_superset_role_ids_to_projects.

Revision ID: 869965e2ceda
Revises: 93d8a6db1803
Create Date: 2026-05-07 11:36:20.165871

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "869965e2ceda"
down_revision: Union[str, None] = "93d8a6db1803"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade for 869965e2ceda."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("superset_view_role_id", sa.Integer(), nullable=True))
    op.add_column("projects", sa.Column("superset_edit_role_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade for 869965e2ceda."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "superset_edit_role_id")
    op.drop_column("projects", "superset_view_role_id")
    # ### end Alembic commands ###
