apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-api-main-ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingressClassName }}
    nginx.ingress.kubernetes.io/rewrite-target: /
    {{- if .Values.use_local_insecure_auth }}
    nginx.ingress.kubernetes.io/auth-url: http://{{ .Release.Name }}-api-service.{{ .Release.Namespace }}.svc.cluster.local/oauth2/insecure_auth
    {{- else }}
    nginx.ingress.kubernetes.io/auth-url: http://{{ .Release.Name }}-oauth2-proxy.{{ .Release.Namespace }}.svc.cluster.local/oauth2/auth
    {{- end }}
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.api.proxyBodySize }}
    nginx.ingress.kubernetes.io/proxy-buffer-size: {{ .Values.api.proxyBufferSize }}
    nginx.ingress.kubernetes.io/proxy-connect-timeout: {{ .Values.api.proxyConnectTimeout }}
    nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-groups, x-auth-request-email"
    {{- if .Values.traefik_ingress }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-{{ .Release.Name }}-forward-auth@kubernetescrd
    {{- end }}
    {{- if .Values.cert_issuer.enabled }}
    cert-manager.io/issuer: {{ .Values.cert_issuer.issuer_name }}
    {{- end }}
    {{- include "phoenixmain.ingress_cors" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  {{- if .Values.cert_issuer.enabled }}
  tls:
  - hosts:
      - api.{{ .Values.base_host }}
    secretName: api-main-ingress-phoenix-tls
  {{- end }}
  rules:
    - host: api.{{ .Values.base_host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-api-service
                port:
                  number: 80
