{{- if .Values.baseJobTemplate.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: phoenix-base-job-template
data:
  baseJobTemplate.json: |
    {
      "variables": {
        "type": "object",
        "properties": {
          "env": {
            "type": "object",
            "title": "Environment Variables",
            "description": "Environment variables to set when starting a flow run.",
            "additionalProperties": {
              "type": "string"
            }
          },
          "resources": {
            "type": "object",
            "title": "Resources",
            "description": "Resources to set when starting a flow run.",
            "additionalProperties": {
              "type": "object",
              "properties": {
                "requests": {
                  "type": "object",
                  "properties": {
                    "cpu": {
                      "type": "string",
                      "title": "CPU Requests"
                    },
                    "memory": {
                      "type": "string",
                      "title": "Memory Requests"
                    }
                  },
                  "required": ["cpu", "memory"]
                },
                "limits": {
                  "type": "object",
                  "properties": {
                    "cpu": {
                      "type": "string",
                      "title": "CPU Limits"
                    },
                    "memory": {
                      "type": "string",
                      "title": "Memory Limits"
                    }
                  },
                  "required": ["cpu", "memory"]
                }
              }
            },
            "default": {
              "requests": {
                "cpu": {{ .Values.baseJobTemplate.defaultResources.requests.cpu | quote }},
                "memory": {{ .Values.baseJobTemplate.defaultResources.requests.memory | quote }}
              },
              "limits": {
                "cpu": {{ .Values.baseJobTemplate.defaultResources.limits.cpu | quote }},
                "memory": {{ .Values.baseJobTemplate.defaultResources.limits.memory | quote }}
              }
            }
          },
          "name": {
            "type": "string",
            "title": "Name",
            "description": "Name given to infrastructure created by a worker."
          },
          "image": {
            "type": "string",
            "title": "Image",
            "default": {{ .Values.baseJobTemplate.defaultImage | quote }},
            "example": "docker.io/prefecthq/prefect:2-latest",
            "description": "The image reference of a container image to use for created jobs. If not set, the latest Prefect image will be used."
          },
          "labels": {
            "type": "object",
            "title": "Labels",
            "description": "Labels applied to infrastructure created by a worker.",
            "additionalProperties": {
              "type": "string"
            }
          },
          "command": {
            "type": "string",
            "title": "Command",
            "description": "The command to use when starting a flow run. In most cases, this should be left blank and the command will be automatically generated by the worker."
          },
          "namespace": {
            "type": "string",
            "title": "Namespace",
            "default": {{ .Release.Namespace | quote }},
            "description": "The Kubernetes namespace to create jobs within."
          },
          "stream_output": {
            "type": "boolean",
            "title": "Stream Output",
            "default": true,
            "description": "If set, output will be streamed from the job to local standard output."
          },
          "cluster_config": {
            "allOf": [
              {
                "$ref": "#/definitions/KubernetesClusterConfig"
              }
            ],
            "title": "Cluster Config",
            "description": "The Kubernetes cluster config to use for job creation."
          },
          "finished_job_ttl": {
            "type": "integer",
            "title": "Finished Job TTL",
            "default": {{ .Values.baseJobTemplate.defaultFinishedJobTTL }},
            "description": "The number of seconds to retain jobs after completion. If set, finished jobs will be cleaned up by Kubernetes after the given delay. If not set, jobs will be retained indefinitely."
          },
          "image_pull_policy": {
            "enum": [
              "IfNotPresent",
              "Always",
              "Never"
            ],
            "type": "string",
            "title": "Image Pull Policy",
            "default": {{ .Values.baseJobTemplate.defaultImagePullPolicy | quote }},
            "description": "The Kubernetes image pull policy to use for job containers."
          },
          "service_account_name": {
            "type": "string",
            "title": "Service Account Name",
            "description": "The Kubernetes service account to use for job creation."
          },
          "job_watch_timeout_seconds": {
            "type": "integer",
            "title": "Job Watch Timeout Seconds",
            "description": "Number of seconds to wait for each event emitted by a job before timing out. If not set, the worker will wait for each event indefinitely."
          },
          "pod_watch_timeout_seconds": {
            "type": "integer",
            "title": "Pod Watch Timeout Seconds",
            "default": {{ .Values.baseJobTemplate.defaultPodWatchTimeoutSeconds }},
            "description": "Number of seconds to watch for pod creation before timing out."
          }
        },
        "definitions": {
          "KubernetesClusterConfig": {
            "type": "object",
            "title": "KubernetesClusterConfig",
            "required": [
              "config",
              "context_name"
            ],
            "properties": {
              "config": {
                "type": "object",
                "title": "Config",
                "description": "The entire contents of a kubectl config file."
              },
              "context_name": {
                "type": "string",
                "title": "Context Name",
                "description": "The name of the kubectl context to use."
              }
            },
            "description": "Stores configuration for interaction with Kubernetes clusters.\n\nSee `from_file` for creation.",
            "secret_fields": [],
            "block_type_slug": "kubernetes-cluster-config",
            "block_schema_references": {}
          }
        },
        "description": "Default variables for the Kubernetes worker.\n\nThe schema for this class is used to populate the `variables` section of the default\nbase job template."
      },
      "job_configuration": {
        "env": "{{`{{ env }}`}}",
        "name": "{{`{{ name }}`}}",
        "labels": "{{`{{ labels }}`}}",
        "command": "{{`{{ command }}`}}",
        "namespace": "{{`{{ namespace }}`}}",
        "job_manifest": {
          "kind": "Job",
          "spec": {
            "template": {
              "spec": {
                "volumes": [
                  {{- if .Values.gcp_service_account.enabled }}
                  {
                    "name": "gcp-creds",
                    "secret": {
                      "secretName": {{ tpl (.Values.gcp_service_account.secret_name) . | quote }}
                    }
                  }
                  {{- end }}
                ],
                "containers": [
                  {
                    "env": [
                      {
                        "name": "SQLALCHEMY_DATABASE_URI",
                        "valueFrom": {
                          "secretKeyRef": {
                            "key": "SQLALCHEMY_DATABASE_URI",
                            "name": {{ tpl (.Values.api.secretKey) . | quote }}
                          }
                        }
                      },
                      {{- if .Values.api.apify_api_keys.enabled }}
                      {
                        "name": "APIFY_API_KEYS",
                        "valueFrom": {
                          "secretKeyRef": {
                            "key": {{ .Values.api.apify_api_keys.secret_key | quote }},
                            "name": {{ tpl ( .Values.api.apify_api_keys.secret_name ) . | quote }}
                          }
                        }
                      },
                      {{- end }}
                      {{- if .Values.api.huggingFaceToken.enabled }}
                      {
                        "name": "HF_TOKEN",
                        "valueFrom": {
                          "secretKeyRef": {
                            "key": {{ .Values.api.huggingFaceToken.secretKey | quote }},
                            "name": {{ tpl ( .Values.api.huggingFaceToken.secretName ) . | quote }}
                          }
                        }
                      },
                      {{- end }}
                      {
                        "name": "HF_GCS_BUCKET_NAME",
                        "value": {{ .Values.api.hfGcsBucketName | quote }}
                      },
                      {{- if .Values.api.hfFlowName }}
                      {
                        "name": "HF_FLOW_NAME",
                        "value": {{ .Values.api.hfFlowName | quote }}
                      },
                      {{- end }}
                      {{- if .Values.api.hfFlowTimeoutSeconds }}
                      {
                        "name": "HF_FLOW_TIMEOUT_SECONDS",
                        "value": {{ .Values.api.hfFlowTimeoutSeconds | quote }}
                      },
                      {{- end }}
                      {{- if .Values.api.danekApiTokens.enabled }}
                      {
                        "name": "DANEK_API_TOKENS",
                        "valueFrom": {
                          "secretKeyRef": {
                            "key": {{ .Values.api.danekApiTokens.secretKey | quote }},
                            "name": {{ tpl ( .Values.api.danekApiTokens.secretName ) . | quote }}
                          }
                        }
                      },
                      {{- end }}
                      {{- if .Values.gcp_service_account.enabled }}
                      {
                        "name": "GOOGLE_APPLICATION_CREDENTIALS",
                        "value": "/var/secrets/google/{{ .Values.gcp_service_account.secret_key }}"
                      },
                      {{- end }}
                      {{- if .Values.api.prefectDefaultResultStorageBlock }}
                      {
                        "name": "PREFECT_RESULTS_PERSIST_BY_DEFAULT",
                        "value": "true"
                      },
                      {
                        "name": "PREFECT_DEFAULT_RESULT_STORAGE_BLOCK",
                        "value": {{ .Values.api.prefectDefaultResultStorageBlock | quote }}
                      },
                      {{- end }}
                      {{- if .Values.api.manualUploadStorageUrl }}
                      {
                        "name": "MANUAL_UPLOAD_STORAGE_URL",
                        "value": {{ .Values.api.manualUploadStorageUrl | quote }}
                      },
                      {{- end }}
                      {{- if .Values.api.apifyTimeoutSecs }}
                      {
                        "name": "APIFY_TIMEOUT_SECS",
                        "value": {{ .Values.api.apifyTimeoutSecs | quote }}
                      },
                      {{- end }}
                      {{- if .Values.api.apifyWaitSecs }}
                      {
                        "name": "APIFY_WAIT_SECS",
                        "value": {{ .Values.api.apifyWaitSecs | quote }}
                      },
                      {{- end }}
                      {{- if .Values.api.innerFlowTimeoutSecs }}
                      {
                        "name": "INNER_FLOW_TIMEOUT_SECS",
                        "value": {{ .Values.api.innerFlowTimeoutSecs | quote }}
                      },
                      {{- end }}
                      {{- if .Values.api.defaultBatchOfBatchesSize }}
                      {
                        "name": "DEFAULT_BATCH_OF_BATCHES_SIZE",
                        "value": {{ .Values.api.defaultBatchOfBatchesSize | quote }}
                      },
                      {{- end }}
                      {{- if .Values.api.perspectiveApiKey }}
                      {
                        "name": "PERSPECTIVE_API_KEY",
                        "valueFrom": {
                          "secretKeyRef": {
                            "key": {{ .Values.perspectiveApiKey.secret_key | quote }},
                            "name": {{ tpl ( .Values.perspectiveApiKey.secret_name ) . | quote }}
                          }
                        }
                      },
                      {{- end }}
                      {{- if .Values.api.perspectiveApiMaxParallelWorkers }}
                      {
                        "name": "PERSPECTIVE_API_MAX_PARALLEL_WORKERS",
                        "value": {{ .Values.api.perspectiveApiMaxParallelWorkers | quote }}
                      },
                      {{- end }}
                      {{- if .Values.api.perspectiveApiRequestLimitForPeriod }}
                      {
                        "name": "PERSPECTIVE_API_REQUEST_LIMIT_FOR_PERIOD",
                        "value": {{ .Values.api.perspectiveApiRequestLimitForPeriod | quote }}
                      },
                      {{- end }}
                      {{- if .Values.api.perspectiveApiRequestLimitPeriodSeconds }}
                      {
                        "name": "PERSPECTIVE_API_REQUEST_LIMIT_PERIOD_SECONDS",
                        "value": {{ .Values.api.perspectiveApiRequestLimitPeriodSeconds | quote }}
                      },
                      {{- end }}
                      {{- if .Values.api.addBigQueryRateLimitsOnProjectCreation }}
                      {
                        "name": "ADD_BIG_QUERY_RATE_LIMITS_ON_PROJECT_CREATION",
                        "value": {{ .Values.api.addBigQueryRateLimitsOnProjectCreation | quote }}
                      },
                      {{- end }}
                      {{- if .Values.api.supersetApiUrl }}
                      {
                        "name": "SUPERSET_API_URL",
                        "value": {{ tpl ( .Values.api.supersetApiUrl ) . | quote }}
                      },
                      {{- end }}
                      {{- if .Values.api.supersetDatabaseUuid }}
                      {
                        "name": "SUPERSET_DATABASE_UUID",
                        "value": {{ .Values.api.supersetDatabaseUuid | quote }}
                      },
                      {{- end }}
                      {{- if .Values.api.supersetDatabaseSqlalchemyUri }}
                      {
                        "name": "SUPERSET_DATABASE_SQLALCHEMY_URI",
                        "value": {{ .Values.api.supersetDatabaseSqlalchemyUri | quote }}
                      },
                      {
                        "name": "SUPERSET_SERVICE_ACCOUNT_EMAIL",
                        "value": {{ .Values.api.supersetServiceAccountEmail | quote }}
                      },
                      {{- end }}
                      {{- if .Values.api.danekCostPer100kResultsDict }}
                      {
                        "name": "DANEK_COST_PER_100K_RESULTS_DICT",
                        "value": {{ .Values.api.danekCostPer100kResultsDict | quote }}
                      },
                      {{- end }}
                      {
                        "name": "USE_MOCK_DANEK",
                        "value": {{ .Values.api.useMockDanek | quote }}
                      },
                      {
                        "name": "USE_MOCK_APIFY",
                        "value": {{ .Values.api.use_mock_apify | quote }}
                      }
                    ],
                    "args": "{{`{{ command }}`}}",
                    "name": "prefect-job",
                    "image": "{{`{{ image }}`}}",
                    "resources": "{{`{{ resources }}`}}",
                    "volumeMounts": [
                      {{- if .Values.gcp_service_account.enabled }}
                      {
                        "name": "gcp-creds",
                        "readOnly": true,
                        "mountPath": "/var/secrets/google"
                      }
                      {{- end }}
                    ],
                    "imagePullPolicy": "{{`{{ image_pull_policy }}`}}"
                  }
                ],
                "completions": 1,
                "parallelism": 1,
                "restartPolicy": "Never",
                "serviceAccountName": "{{`{{ service_account_name }}`}}"
              }
            },
            "backoffLimit": 0,
            "ttlSecondsAfterFinished": "{{`{{ finished_job_ttl }}`}}"
          },
          "metadata": {
            "labels": "{{`{{ labels }}`}}",
            "namespace": "{{`{{ namespace }}`}}",
            "generateName": "{{`{{ name }}`}}-"
          },
          "apiVersion": "batch/v1"
        },
        "stream_output": "{{`{{ stream_output }}`}}",
        "cluster_config": "{{`{{ cluster_config }}`}}",
        "job_watch_timeout_seconds": "{{`{{ job_watch_timeout_seconds }}`}}",
        "pod_watch_timeout_seconds": "{{`{{ pod_watch_timeout_seconds }}`}}"
      }
    }
{{- end }}
