slice_name: Raw Data
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 245__table
  viz_type: table
  slice_id: 4824
  query_mode: aggregate
  groupby:
  - post_date
  - platform
  - post_author_name_pi
  - post_author_class
  - post_author_link_pi
  - post_text_pi
  - post_class
  - post_like_count
  - post_comment_count
  - post_share_count
  - facebook_video_views
  - tiktok_post_plays
  time_grain_sqla: P1D
  temporal_columns_lookup:
    post_date: true
    post_datetime: true
    comment_date: true
    comment_datetime: true
    phoenix_processed_at: true
  all_columns: []
  percent_metrics: []
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: post_datetime
  order_by_cols: []
  row_limit: 1000
  table_timestamp_format: smart_date
  page_length: 200
  include_search: true
  allow_render_html: true
  show_cell_bars: true
  color_pn: true
  comparison_color_scheme: Green
  conditional_formatting: []
  comparison_type: values
  extra_form_data: {}
  dashboards:
  - 336
query_context: '{"datasource":{"id":245,"type":"table"},"force":false,"queries":[{"filters":[{"col":"post_datetime","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1D","columnType":"BASE_AXIS","sqlExpression":"post_date","label":"post_date","expressionType":"SQL"},"platform","post_author_name_pi","post_author_class","post_author_link_pi","post_text_pi","post_class","post_like_count","post_comment_count","post_share_count","facebook_video_views","tiktok_post_plays"],"metrics":[],"orderby":[],"annotation_layers":[],"row_limit":1000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[],"time_offsets":[]}],"form_data":{"datasource":"245__table","viz_type":"table","slice_id":4824,"query_mode":"aggregate","groupby":["post_date","platform","post_author_name_pi","post_author_class","post_author_link_pi","post_text_pi","post_class","post_like_count","post_comment_count","post_share_count","facebook_video_views","tiktok_post_plays"],"time_grain_sqla":"P1D","temporal_columns_lookup":{"post_date":true,"post_datetime":true,"comment_date":true,"comment_datetime":true,"phoenix_processed_at":true},"all_columns":[],"percent_metrics":[],"adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","expressionType":"SIMPLE","operator":"TEMPORAL_RANGE","subject":"post_datetime"}],"order_by_cols":[],"row_limit":1000,"table_timestamp_format":"smart_date","page_length":200,"include_search":true,"allow_render_html":true,"show_cell_bars":true,"color_pn":true,"comparison_color_scheme":"Green","conditional_formatting":[],"comparison_type":"values","extra_form_data":{},"dashboards":[336],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 418b7158-a199-4fae-9603-94117f2ac157
version: 1.0.0
dataset_uuid: dd3e9568-93f9-4cbd-8ec7-001ce0758de4
