{{- if .Values.baseJobTemplate.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: phoenix-hf-classifier-base-job-template
data:
  baseJobTemplate.json: |
    {
      "variables": {
        "type": "object",
        "properties": {
          "env": {
            "type": "object",
            "title": "Environment Variables",
            "description": "Environment variables to set when starting a flow run.",
            "additionalProperties": {
              "type": "string"
            }
          },
          "name": {
            "type": "string",
            "title": "Name",
            "description": "Name given to infrastructure created by a worker."
          },
          "image": {
            "type": "string",
            "title": "Image",
            "default": {{ .Values.baseJobTemplate.defaultImage | quote }},
            "example": "docker.io/prefecthq/prefect:2-latest",
            "description": "The image reference of a container image to use for created jobs. If not set, the latest Prefect image will be used."
          },
          "labels": {
            "type": "object",
            "title": "Labels",
            "description": "Labels applied to infrastructure created by a worker.",
            "additionalProperties": {
              "type": "string"
            }
          },
          "command": {
            "type": "string",
            "title": "Command",
            "description": "The command to use when starting a flow run. In most cases, this should be left blank and the command will be automatically generated by the worker."
          },
          "namespace": {
            "type": "string",
            "title": "Namespace",
            "default": {{ .Release.Namespace | quote }},
            "description": "The Kubernetes namespace to create jobs within."
          },
          "stream_output": {
            "type": "boolean",
            "title": "Stream Output",
            "default": true,
            "description": "If set, output will be streamed from the job to local standard output."
          },
          "cluster_config": {
            "allOf": [
              {
                "$ref": "#/definitions/KubernetesClusterConfig"
              }
            ],
            "title": "Cluster Config",
            "description": "The Kubernetes cluster config to use for job creation."
          },
          "finished_job_ttl": {
            "type": "integer",
            "title": "Finished Job TTL",
            "default": {{ .Values.baseJobTemplate.defaultFinishedJobTTL }},
            "description": "The number of seconds to retain jobs after completion. If set, finished jobs will be cleaned up by Kubernetes after the given delay. If not set, jobs will be retained indefinitely."
          },
          "image_pull_policy": {
            "enum": [
              "IfNotPresent",
              "Always",
              "Never"
            ],
            "type": "string",
            "title": "Image Pull Policy",
            "default": {{ .Values.baseJobTemplate.defaultImagePullPolicy | quote }},
            "description": "The Kubernetes image pull policy to use for job containers."
          },
          "service_account_name": {
            "type": "string",
            "title": "Service Account Name",
            "description": "The Kubernetes service account to use for job creation."
          },
          {{- if .Values.baseJobTemplate.tolerations.enabled }}
          "tolerations_key": {
            "type": "string",
            "title": "Toleration Key",
            "default": {{ .Values.baseJobTemplate.tolerations.key | quote }},
            "description": "The key of the toleration."
          },
          "tolerations_operator": {
            "type": "string",
            "title": "Toleration Operator",
            "enum": [
              "Equal",
              "Exists"
            ],
            "default": {{ .Values.baseJobTemplate.tolerations.operator | quote }},
            "description": "The operator of the toleration."
          },
          "tolerations_value": {
            "type": "string",
            "title": "Toleration Value",
            "default": {{ .Values.baseJobTemplate.tolerations.value | quote }},
            "description": "The value of the toleration. If not set, the toleration will match all values."
          },
          "tolerations_effect": {
            "type": "string",
            "title": "Toleration Effect",
            "enum": [
              null,
              "NoSchedule",
              "PreferNoSchedule",
              "NoExecute"
            ],
            "default": {{ .Values.baseJobTemplate.tolerations.effect | quote }},
            "description": "`NoSchedule`, `PreferNoSchedule`, or `NoExecute` effect of the toleration."
          },
          {{- end }}
          {{- if .Values.baseJobTemplate.nodeSelector.enabled }}
          "node_selector": {
            "type": "object",
            "title": "Node Selector",
            "default": {{ .Values.baseJobTemplate.nodeSelector.default | toJson }},
            "description": "Node selector to use for job creation. This is a map of key-value pairs that will be used to select nodes for job execution.",
            "additionalProperties": {
              "type": "string"
            }
          },
          {{- end }}
          "job_watch_timeout_seconds": {
            "type": "integer",
            "title": "Job Watch Timeout Seconds",
            "description": "Number of seconds to wait for each event emitted by a job before timing out. If not set, the worker will wait for each event indefinitely."
          },
          "pod_watch_timeout_seconds": {
            "type": "integer",
            "title": "Pod Watch Timeout Seconds",
            "default": {{ .Values.baseJobTemplate.defaultPodWatchTimeoutSeconds }},
            "description": "Number of seconds to watch for pod creation before timing out."
          },
          "default_result_storage_block": {
            "type": "string",
            "title": "Default Result Storage Block",
            {{- if .Values.baseJobTemplate.defaultResultStorageBlock }}
            "default": {{ .Values.baseJobTemplate.defaultResultStorageBlock | quote }},
            {{- end }}
            "description": "The block name of the default result storage to use for flow runs created by this worker. If not set, the worker will use the default result storage configured in Prefect."
          },
          "results_persist_by_default": {
            "type": "string",
            "title": "Results Persist By Default",
            "default": {{ .Values.baseJobTemplate.resultsPersistByDefault | quote }},
            "description": "If set, results will be persisted by default for flow runs created by this worker. If not set, results will not be persisted by default."
          }
        },
        "definitions": {
          "KubernetesClusterConfig": {
            "type": "object",
            "title": "KubernetesClusterConfig",
            "required": [
              "config",
              "context_name"
            ],
            "properties": {
              "config": {
                "type": "object",
                "title": "Config",
                "description": "The entire contents of a kubectl config file."
              },
              "context_name": {
                "type": "string",
                "title": "Context Name",
                "description": "The name of the kubectl context to use."
              }
            },
            "description": "Stores configuration for interaction with Kubernetes clusters.\n\nSee `from_file` for creation.",
            "secret_fields": [],
            "block_type_slug": "kubernetes-cluster-config",
            "block_schema_references": {}
          }
        },
        "description": "Default variables for the Kubernetes worker.\n\nThe schema for this class is used to populate the `variables` section of the default\nbase job template."
      },
      "job_configuration": {
        "env": "{{`{{ env }}`}}",
        "name": "{{`{{ name }}`}}",
        "labels": "{{`{{ labels }}`}}",
        "command": "{{`{{ command }}`}}",
        "namespace": "{{`{{ namespace }}`}}",
        "job_manifest": {
          "kind": "Job",
          "spec": {
            "template": {
              "spec": {
                "volumes": [
                  {{- if .Values.gcpServiceAccount.enabled }}
                  {
                    "name": "gcp-creds",
                    "secret": {
                      "secretName": {{ tpl (.Values.gcpServiceAccount.secretName) . | quote }}
                    }
                  }
                  {{- end }}
                ],
                {{- if .Values.baseJobTemplate.tolerations.enabled }}
                "tolerations": [
                  {
                    "key": "{{`{{ tolerations_key }}`}}",
                    "operator": "{{`{{ tolerations_operator }}`}}",
                    "value": "{{`{{ tolerations_value }}`}}",
                    "effect": "{{`{{ tolerations_effect }}`}}"
                  }
                ],
                {{- end }}
                {{- if .Values.baseJobTemplate.nodeSelector.enabled }}
                "nodeSelector": "{{`{{ node_selector }}`}}",
                {{- end }}
                "containers": [
                  {
                    "env": [
                      {{- if .Values.huggingFaceToken.enabled }}
                      {
                        "name": "HF_TOKEN",
                        "valueFrom": {
                          "secretKeyRef": {
                            "name": {{ tpl (.Values.huggingFaceToken.secretName) . | quote }},
                            "key": {{ tpl (.Values.huggingFaceToken.secretKey) . | quote }}
                          }
                        }
                      },
                      {{- end }}
                      {{- if .Values.gcpServiceAccount.enabled }}
                      {
                        "name": "GOOGLE_APPLICATION_CREDENTIALS",
                        "value": "/var/secrets/google/{{ .Values.gcpServiceAccount.secretKey }}"
                      },
                      {{- end }}
                      {{- if .Values.gcpServiceAccount.project }}
                      {
                        "name": "GOOGLE_CLOUD_PROJECT",
                        "value": "{{ .Values.gcpServiceAccount.project }}"
                      },
                      {{- end }}
                      {
                        "name": "PREFECT_DEFAULT_RESULT_STORAGE_BLOCK",
                        "value": "{{`{{ default_result_storage_block }}`}}"
                      },
                      {
                        "name": "PREFECT_RESULTS_PERSIST_BY_DEFAULT",
                        "value": "{{`{{ results_persist_by_default }}`}}"
                      }
                    ],
                    "args": "{{`{{ command }}`}}",
                    "name": "prefect-job",
                    "image": "{{`{{ image }}`}}",
                    "volumeMounts": [
                      {{- if .Values.gcpServiceAccount.enabled }}
                      {
                        "name": "gcp-creds",
                        "readOnly": true,
                        "mountPath": "/var/secrets/google"
                      }
                      {{- end }}
                     ],
                    "imagePullPolicy": "{{`{{ image_pull_policy }}`}}"
                  }
                ],
                "completions": 1,
                "parallelism": 1,
                "restartPolicy": "Never",
                "serviceAccountName": "{{`{{ service_account_name }}`}}"
              }
            },
            "backoffLimit": 0,
            "ttlSecondsAfterFinished": "{{`{{ finished_job_ttl }}`}}"
          },
          "metadata": {
            "labels": "{{`{{ labels }}`}}",
            "namespace": "{{`{{ namespace }}`}}",
            "generateName": "{{`{{ name }}`}}-"
          },
          "apiVersion": "batch/v1"
        },
        "stream_output": "{{`{{ stream_output }}`}}",
        "cluster_config": "{{`{{ cluster_config }}`}}",
        "job_watch_timeout_seconds": "{{`{{ job_watch_timeout_seconds }}`}}",
        "pod_watch_timeout_seconds": "{{`{{ pod_watch_timeout_seconds }}`}}"
      }
    }
{{- end }}
