{{- if and .Values.gcpServiceAccount.enabled .Values.gcpServiceAccount.json }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl (.Values.gcpServiceAccount.secretName) . }}
type: Opaque
data:
  {{ .Values.gcpServiceAccount.secretKey }}: {{ .Values.gcpServiceAccount.json | b64enc }}
{{- end }}

{{- if and .Values.huggingFaceToken.enabled .Values.huggingFaceToken.token }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl (.Values.huggingFaceToken.secretName) . }}
type: Opaque
data:
  {{ .Values.huggingFaceToken.secretKey }}: {{ .Values.huggingFaceToken.token | b64enc }}
{{- end }}
